### ISSUE TITLE
Running `ng test` fails to start chrome browser

### ISSUE THREAD

**Issue by danimbrogno** [teracyhq/docker-files#14]
Hi, thanks for the image. I'm having trouble getting `ng test` to run. Here is my docker-compose.yaml:

```
version: '2'
services:
  test-web-app:
    image: teracy/angular-cli
    command:
      - ng
      - test
    working_dir: /usr/src
    volumes:
      - "./:/usr/src"
```

when I run `docker-compose run test-web-app`

I get the output

```
Starting virtual X frame buffer: Xvfb.
Executing command ng test
25 01 2017 14:35:22.023:WARN [karma]: No captured browser, open http://localhost:9876/
25 01 2017 14:35:22.047:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
25 01 2017 14:35:22.049:INFO [launcher]: Launching browser Chrome with unlimited concurrency
25 01 2017 14:35:22.093:INFO [launcher]: Starting browser Chrome
25 01 2017 14:35:22.406:ERROR [launcher]: Cannot start Chrome

25 01 2017 14:35:23.481:INFO [launcher]: Trying to start Chrome again (1/2).
25 01 2017 14:35:23.581:ERROR [launcher]: Cannot start Chrome

25 01 2017 14:35:23.803:INFO [launcher]: Trying to start Chrome again (2/2).
25 01 2017 14:35:23.927:ERROR [launcher]: Cannot start Chrome

25 01 2017 14:35:24.087:ERROR [launcher]: Chrome failed 2 times (cannot start). Giving up.
```
